export async function privilege(prisma: any){
    console.log("Creating Privilege");
    const privilegeData = [
        {
            "id": 1,
            "accessibility": {"modules": [{"name": "Dashboard", "privileges": [{"name": "View Dashboard", "paths": ["/dashboard"]}]}, {"name": "Employees", "privileges": [{"name": "View Employees", "paths": ["/employeemanagement"]}]}, {"name": "Attendance and Time", "privileges": [{"name": "Write Schedules", "paths": ["/api/admin/attendance-time/schedule/add-schedule", "/api/admin/attendance-time/schedule/edit-schedule", "/api/admin/attendance-time/schedule/delete-schedule"]}, {"name": "Read Overtimes", "paths": ["/attendance-time/overtime", "/api/admin/attendance-time/overtime"]}, {"name": "File Overtimes", "paths": ["/api/admin/attendance-time/overtime/file"]}, {"name": "Approve Overtimes", "paths": ["/api/admin/attendance-time/overtime/update"]}, {"name": "Read Holidays", "paths": ["/attendance-time/holidays", "/api/admin/attendance-time/holidays"]}, {"name": "Write Holidays", "paths": ["/api/admin/attendance-time/holidays/create", "/api/admin/attendance-time/holidays/delete"]}]}, {"name": "Benefits", "privileges": [{"name": "View Benefits", "paths": ["/benefits"]}]}, {"name": "Incident", "privileges": [{"name": "Read Incidents", "paths": ["/incident", "/api/admin/incident/reports"]}, {"name": "File Incidents", "paths": ["/api/admin/incident/update", "/api/admin/incident/create"]}]}, {"name": "Leaves", "privileges": [{"name": "Read Leaves", "paths": ["/leaves"]}]}, {"name": "Payroll", "privileges": [{"name": "Read Earnings", "paths": ["/payroll/earnings", "/api/admin/payroll/payhead?type=earning", "/payroll/earnings/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Read Deductions", "paths": ["/payroll/deductions", "/api/admin/payroll/payhead?type=deduction", "/payroll/deductions/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Write Earnings and Deductions", "paths": ["/api/admin/payroll/payhead/upsert-payhead", "/api/admin/payroll/payhead/delete"]}]}, {"name": "Privileges", "privileges": [{"name": "Read Privileges", "paths": ["/privileges/accessibility", "/api/admin/privilege"]}, {"name": "Write Privileges", "paths": ["/api/admin/privilege/create-accessibility", "/api/admin/privilege/update-accessibility", "/api/admin/privilege/delete-accessibility"]}]}, {"name": "Signatories", "privileges": [{"name": "View Signatories", "paths": ["/signatories"]}]}, {"name": "Reports", "privileges": [{"name": "View Reports", "paths": ["/reports"]}]}, {"name": "Trainings and Seminars", "privileges": [{"name": "View Trainings and Seminars", "paths": ["/trainings-and-seminars"]}]}, {"name": "Performance Appraisal", "privileges": [{"name": "View Performance Appraisal", "paths": ["/performance"]}]}, {"name": "Tests", "privileges": [{"name": "View Tests", "paths": ["/test"]}]}], "web_access": true},
            "name": "Finance Access",
            "created_at": new Date(),
            "updated_at": new Date(),
            "deleted_at": null
        },
        {
            "id": 2,
            "accessibility": {"modules": [{"name": "Dashboard", "privileges": [{"name": "View Dashboard", "paths": ["/dashboard"]}]}, {"name": "Employees", "privileges": [{"name": "View Employees", "paths": ["/employeemanagement"]}]}, {"name": "Attendance and Time", "privileges": [{"name": "Read Attendance Logs", "paths": ["/attendance-time/records", "/api/admin/attendance-time/records/"]}, {"name": "Read Schedules", "paths": ["/attendance-time/schedule", "/api/admin/attendance-time/schedule"]}, {"name": "Write Schedules", "paths": ["/api/admin/attendance-time/schedule/add-schedule", "/api/admin/attendance-time/schedule/edit-schedule", "/api/admin/attendance-time/schedule/delete-schedule"]}, {"name": "Read Overtimes", "paths": ["/attendance-time/overtime", "/api/admin/attendance-time/overtime"]}, {"name": "File Overtimes", "paths": ["/api/admin/attendance-time/overtime/file"]}, {"name": "Approve Overtimes", "paths": ["/api/admin/attendance-time/overtime/update"]}, {"name": "Read Holidays", "paths": ["/attendance-time/holidays", "/api/admin/attendance-time/holidays"]}, {"name": "Write Holidays", "paths": ["/api/admin/attendance-time/holidays/upsert", "/api/admin/attendance-time/holidays/delete"]}]}, {"name": "Benefits", "privileges": [{"name": "View Benefits", "paths": ["/benefits"]}]}, {"name": "Incident", "privileges": [{"name": "Read Incidents", "paths": ["/incident", "/api/admin/incident/reports"]}, {"name": "File Incidents", "paths": ["/api/admin/incident/update", "/api/admin/incident/upsert"]}]}, {"name": "Leaves", "privileges": [{"name": "Read Leaves", "paths": ["/leaves"]}]}, {"name": "Payroll", "privileges": [{"name": "Read Earnings", "paths": ["/payroll/earnings", "/api/admin/payroll/payhead?type=earning", "/payroll/earnings/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Read Deductions", "paths": ["/payroll/deductions", "/api/admin/payroll/payhead?type=deduction", "/payroll/deductions/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Write Earnings and Deductions", "paths": ["/api/admin/payroll/payhead/upsert-payhead", "/api/admin/payroll/payhead/delete"]}]}, {"name": "Privileges", "privileges": [{"name": "Read Privileges", "paths": ["/privileges/accessibility", "/api/admin/privilege"]}, {"name": "Write Privileges", "paths": ["/api/admin/privilege/upsert-accessibility", "/api/admin/privilege/update-accessibility", "/api/admin/privilege/delete-accessibility"]}]}, {"name": "Signatories", "privileges": [{"name": "View Signatories", "paths": ["/signatories"]}]}, {"name": "Reports", "privileges": [{"name": "View Reports", "paths": ["/reports"]}]}, {"name": "Trainings and Seminars", "privileges": [{"name": "View Trainings and Seminars", "paths": ["/trainings-and-seminars"]}]}, {"name": "Performance Appraisal", "privileges": [{"name": "View Performance Appraisal", "paths": ["/performance"]}]}, {"name": "Tests", "privileges": [{"name": "View Tests", "paths": ["/test"]}]}], "web_access": true},
            "name": "Admin Access",
            "created_at": new Date(),
            "updated_at": new Date(),
            "deleted_at": null
        },
        {
            "id": 3,
            "accessibility": {"modules": [{"name": "Dashboard", "privileges": [{"name": "View Dashboard", "paths": ["/dashboard"]}]}, {"name": "Employees", "privileges": [{"name": "View Employees", "paths": ["/employeemanagement"]}]}, {"name": "Attendance and Time", "privileges": [{"name": "Read Attendance Logs", "paths": ["/attendance-time/records", "/api/admin/attendance-time/records/"]}, {"name": "Read Schedules", "paths": ["/attendance-time/schedule", "/api/admin/attendance-time/schedule"]}, {"name": "Write Schedules", "paths": ["/api/admin/attendance-time/schedule/add-schedule", "/api/admin/attendance-time/schedule/edit-schedule", "/api/admin/attendance-time/schedule/delete-schedule"]}, {"name": "Read Overtimes", "paths": ["/attendance-time/overtime", "/api/admin/attendance-time/overtime"]}, {"name": "File Overtimes", "paths": ["/api/admin/attendance-time/overtime/file"]}, {"name": "Approve Overtimes", "paths": ["/api/admin/attendance-time/overtime/update"]}, {"name": "Read Holidays", "paths": ["/attendance-time/holidays", "/api/admin/attendance-time/holidays"]}, {"name": "Write Holidays", "paths": ["/api/admin/attendance-time/holidays/upsert", "/api/admin/attendance-time/holidays/delete"]}]}, {"name": "Benefits", "privileges": [{"name": "View Benefits", "paths": ["/benefits"]}]}, {"name": "Incident", "privileges": [{"name": "Read Incidents", "paths": ["/incident", "/api/admin/incident/reports"]}, {"name": "File Incidents", "paths": ["/api/admin/incident/update", "/api/admin/incident/upsert"]}]}, {"name": "Leaves", "privileges": [{"name": "Read Leaves", "paths": ["/leaves"]}]}, {"name": "Payroll", "privileges": [{"name": "Read Earnings", "paths": ["/payroll/earnings", "/api/admin/payroll/payhead?type=earning", "/payroll/earnings/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Read Deductions", "paths": ["/payroll/deductions", "/api/admin/payroll/payhead?type=deduction", "/payroll/deductions/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Write Earnings and Deductions", "paths": ["/api/admin/payroll/payhead/upsert-payhead", "/api/admin/payroll/payhead/delete"]}]}, {"name": "Privileges", "privileges": [{"name": "Read Privileges", "paths": ["/privileges/accessibility", "/api/admin/privilege"]}, {"name": "Write Privileges", "paths": ["/api/admin/privilege/upsert-accessibility", "/api/admin/privilege/update-accessibility", "/api/admin/privilege/delete-accessibility"]}]}, {"name": "Signatories", "privileges": [{"name": "View Signatories", "paths": ["/signatories"]}]}, {"name": "Reports", "privileges": [{"name": "View Reports", "paths": ["/reports"]}]}, {"name": "Trainings and Seminars", "privileges": [{"name": "View Trainings and Seminars", "paths": ["/trainings-and-seminars"]}]}, {"name": "Performance Appraisal", "privileges": [{"name": "View Performance Appraisal", "paths": ["/performance"]}]}, {"name": "Tests", "privileges": [{"name": "View Tests", "paths": ["/test"]}]}], "web_access": true},
            "name": "HR Management",
            "created_at": new Date(),
            "updated_at": new Date(),
            "deleted_at": null
        },
        {
            "id": 4,
            "accessibility": {"modules": [{"name": "Dashboard", "privileges": [{"name": "View Dashboard", "paths": ["/dashboard"]}]}, {"name": "Employees", "privileges": [{"name": "View Employees", "paths": ["/employeemanagement"]}]}, {"name": "Attendance and Time", "privileges": [{"name": "Read Attendance Logs", "paths": ["/attendance-time/records", "/api/admin/attendance-time/records/"]}, {"name": "Read Schedules", "paths": ["/attendance-time/schedule", "/api/admin/attendance-time/schedule"]}, {"name": "Write Schedules", "paths": ["/api/admin/attendance-time/schedule/add-schedule", "/api/admin/attendance-time/schedule/edit-schedule", "/api/admin/attendance-time/schedule/delete-schedule"]}, {"name": "Read Overtimes", "paths": ["/attendance-time/overtime", "/api/admin/attendance-time/overtime"]}, {"name": "File Overtimes", "paths": ["/api/admin/attendance-time/overtime/file"]}, {"name": "Approve Overtimes", "paths": ["/api/admin/attendance-time/overtime/update"]}, {"name": "Read Holidays", "paths": ["/attendance-time/holidays", "/api/admin/attendance-time/holidays"]}, {"name": "Write Holidays", "paths": ["/api/admin/attendance-time/holidays/create", "/api/admin/attendance-time/holidays/delete"]}]}, {"name": "Benefits", "privileges": [{"name": "View Benefits", "paths": ["/benefits"]}]}, {"name": "Incident", "privileges": [{"name": "Read Incidents", "paths": ["/incident", "/api/admin/incident/reports"]}, {"name": "File Incidents", "paths": ["/api/admin/incident/update", "/api/admin/incident/create"]}]}, {"name": "Leaves", "privileges": [{"name": "Read Leaves", "paths": ["/leaves"]}]}, {"name": "Payroll", "privileges": [{"name": "Read Earnings", "paths": ["/payroll/earnings", "/api/admin/payroll/payhead?type=earning", "/payroll/earnings/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Read Deductions", "paths": ["/payroll/deductions", "/api/admin/payroll/payhead?type=deduction", "/payroll/deductions/manage", "/api/admin/payroll/payhead/read"]}, {"name": "Write Earnings and Deductions", "paths": ["/api/admin/payroll/payhead/upsert-payhead", "/api/admin/payroll/payhead/delete"]}]}, {"name": "Privileges", "privileges": [{"name": "Read Privileges", "paths": ["/privileges/accessibility", "/api/admin/privilege"]}, {"name": "Write Privileges", "paths": ["/api/admin/privilege/create-accessibility", "/api/admin/privilege/update-accessibility", "/api/admin/privilege/delete-accessibility"]}]}, {"name": "Signatories", "privileges": [{"name": "View Signatories", "paths": ["/signatories"]}]}, {"name": "Reports", "privileges": [{"name": "View Reports", "paths": ["/reports"]}]}, {"name": "Trainings and Seminars", "privileges": [{"name": "View Trainings and Seminars", "paths": ["/trainings-and-seminars"]}]}, {"name": "Performance Appraisal", "privileges": [{"name": "View Performance Appraisal", "paths": ["/performance"]}]}, {"name": "Tests", "privileges": [{"name": "View Tests", "paths": ["/test"]}]}], "web_access": true},
            "name": "Read-Only Access",
            "created_at": new Date(),
            "updated_at": new Date(),
            "deleted_at": null
        },
        {
            "id": 5,
            "accessibility": {"modules": [{"name": "Dashboard", "privileges": [{"name": "View Dashboard", "paths": ["/dashboard"]}]}, {"name": "Employees", "privileges": [{"name": "View Employees", "paths": ["/employeemanagement", "/"]}]}], "web_access": true},
            "name": "Initial Account",
            "created_at": new Date(),
            "updated_at": new Date(),
            "deleted_at": null
        }
    ]
    await prisma.sys_privileges.createMany({
        data: privilegeData,
    });
    console.log("Finished Privilege");
}